### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by jamesmstone** [arvitaly/polymer-relay#1]
Hi I was wondering if this is still under active development? or if it was abandoned? and if abandoned why? 

The reason I'm asking as this sounds like a nice way of using `graphql` with `polymer`. Which to (possibly ignorant) me sounds like a great idea.

**Comment by arvitaly** [comment]
Hi! Now Relay dependence on React very much, so it not good idea, really. May be, when Relay 2  will be released with new API https://github.com/facebook/relay/issues/1369

**Comment by jamesmstone** [comment]
very interesting, I feared that might be the case. Shame relay is so linked to react, but really nice to see they are possibly changing it in the future. cheers
